// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2MyeWmwVfP38jssdo2FXDduHww4WYEk',
    appId: '1:191703733211:web:40d88c0808cfdc383b8dfe',
    messagingSenderId: '191703733211',
    projectId: 'badmintion',
    authDomain: 'badmintion.firebaseapp.com',
    storageBucket: 'badmintion.firebasestorage.app',
    measurementId: 'G-51WKTPRCER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACLFH88kEKs7I_smWQ7afLx01KcvsSvE0',
    appId: '1:191703733211:android:5b1daacff270e9fb3b8dfe',
    messagingSenderId: '191703733211',
    projectId: 'badmintion',
    storageBucket: 'badmintion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdiOZIs1s4om6WzsMwFE_u3y_3VCYJ7hw',
    appId: '1:191703733211:ios:71fd789ac3d21bef3b8dfe',
    messagingSenderId: '191703733211',
    projectId: 'badmintion',
    storageBucket: 'badmintion.firebasestorage.app',
    iosBundleId: 'com.example.badmintonAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdiOZIs1s4om6WzsMwFE_u3y_3VCYJ7hw',
    appId: '1:191703733211:ios:71fd789ac3d21bef3b8dfe',
    messagingSenderId: '191703733211',
    projectId: 'badmintion',
    storageBucket: 'badmintion.firebasestorage.app',
    iosBundleId: 'com.example.badmintonAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp2MyeWmwVfP38jssdo2FXDduHww4WYEk',
    appId: '1:191703733211:web:2f50cf1dd0410c4d3b8dfe',
    messagingSenderId: '191703733211',
    projectId: 'badmintion',
    authDomain: 'badmintion.firebaseapp.com',
    storageBucket: 'badmintion.firebasestorage.app',
    measurementId: 'G-XNJC7YR82S',
  );
}
